" 
" general config
"
set number                      " Show line numbers
set showmatch                   " When inserting brackets, highlight the matching one
set hlsearch                    " Highlight search results
set incsearch                   " Highlight search results as the search is typed
set showcmd                     " Show command on the bottom
set ruler                       " Show line and cursor position
set colorcolumn=80,120          " Highlight the 80th column
set list
set listchars=tab:>-,trail:·	  " Show tabs and trailing space
set fillchars=vert:\│

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" turn on syntax highlighting
syntax on

" change leader button
let mapleader = "\<Space>"

" turn off swap files
set noswapfile
set nobackup
set nowb

"
" indentation
"
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

" autoindent pasted text
nnoremap p p=`]<C-o>
nnoremap P P=`]<C-o>

"
" plugins
"
call plug#begin('~/.vim/plugged')
 " Useful plugins
 Plug 'scrooloose/nerdtree'
 Plug 'scrooloose/nerdcommenter'
 Plug 'Xuyuanp/nerdtree-git-plugin'

 Plug 'Shougo/neocomplete.vim'

 " Tmux
 Plug 'tmux-plugins/vim-tmux'
 Plug 'christoomey/vim-tmux-navigator'

 " Javascript
 Plug 'pangloss/vim-javascript'
 Plug 'leafgarland/typescript-vim'
 Plug 'mxw/vim-jsx'
 Plug 'othree/yajs.vim'
 Plug 'othree/javascript-libraries-syntax.vim'
call plug#end()

syntax enable

autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

source ~/.dotfiles/vim/splits.vim

nnoremap <Leader>a :Ack!<Space>
