echo "\e[3m$(fortune -sa)\n"

export ZSH=/usr/share/oh-my-zsh/
export EDITOR=/usr/bin/nvim
export TERM="xterm-256color"
export JAVA_HOME=/usr/lib/jvm/default
export ANDROID_SDK_ROOT=/opt/android-sdk/
export npm_config_prefix=~/.npm-global
export PATH="$ANDROID_SDK_ROOT/emulator:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"

zstyle ":completion:*:commands" rehash 1

ZSH_THEME="simple"

DISABLE_LS_COLORS="false"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
DISABLE_AUTO_UPDATE="true"

plugins=(git docker docker-compose zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias vim='nvim'
alias r='ranger'
alias ranger='ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR"'
alias speedtest='curl -o /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'

unsetopt share_history
